### ISSUE TITLE
[Question] How to update the pack in MultMC

### ISSUE THREAD

**Issue by DietmarKrause** [AllTheMods/ATM-Fabric#11]
Do i have to make a new instance and if so what files do i have to copy to the new instance oher than the save folder with the world?

**Comment by DietmarKrause** [comment]
Until now i made a new instance with the 1.3 zip files, started the pack once, after that copied the save folder and the files Options.txt to the new instance. It works but i lost my waypoints. Any ideas what else to copy beside save folder and the options.txt file from the old istanc (1.2) to the new (1.3)?

**Comment by furtabs** [comment]
Currently there is no easy way to do it but we are switching to distribute on Twitch and MultiMC in the upcoming 2.0 update
