### ISSUE TITLE
Wearing helmet makes buckets unusable

### ISSUE THREAD

**Issue by Quu1337** [AllTheMods/ATM-Fabric#12]
Bucket Hat, (+ something else i cant find from mod list) allows you to wear bucket in your helmet slot.
If you are wearing any kind of helmet while right-clicking with bucket, it swaps your helmet and bucket, making using buckets impossible and causing graphical glitches to fluids.
You have to remove helmet to use buckets.
Seems like in singleplayer its enough to disable the mod, but on servers it probably needs to be removed from server as well.

**Comment by furtabs** [comment]
Yeah this mod is garbage lul
