### ISSUE TITLE
Snowdrift

### ISSUE THREAD

**Issue by Quu1337** [AllTheMods/ATM-Fabric#13]
snowdrift.json5

{ 
	// The chance for a snow layer to attempt to appear at a random position in a chunk every tick. 200 is 1/200 chance, or about once every 10 seconds. 20 is about every second.
	"increaseChancePerChunk": 200,
	// The chance for a snow layer to attempt to disappear at a random position in a chunk every tick. 400 is 1/400 chance, or about once every 20 seconds. 20 is about every second.
	"decreaseChancePerChunk": 400,
	// Number of snow layers to keep during snow decay.
	"layersToKeep": 1,
	// Maximum amount of snow layers that is allowed to accumulate at one spot. 8 is the same as a single block.
	"maxLayers": 8,
	// Amount of snow blocks around a position that must be at least the same level of snow in order for snow to pile up.
	"smoothingRequirement": 2
}

Could the "layersToKeep" be changed to 0 or the "decreaseChancePerChunk" changed to smaller?
Theres 1-3 layerrs of snow everywhere in render distance range.

**Comment by profpeculiar** [comment]
Yeah Snowdrift needs to go. It also seems to break lightning storms and turn them into Zeus' personal hate rave/mosh pit with literal constant lightning strikes all over the damn place.

**Comment by furtabs** [comment]
We removed the mod in the upcoming update for the Twitch Launcher.
