### ISSUE TITLE
bioms from the dimension/mod "the Hallow" spreads in the overworld after world generation

### ISSUE THREAD

**Issue by DietmarKrause** [AllTheMods/ATM-Fabric#15]
i report because i couldn't find any advice on the mods page that this is on purpose. It definitly spreads after new load of the world because it happens to a location where i had my spawn and there was nothing like that before that. After several restarts (without crashes or other problems) there was a biome change in some blocks diameter with purple sky. Single player world., Perhaps related: https://github.com/fabric-community/the-hallow/issues/182
EDIT: i found out that the biom change is different: after simple save / reload or the world the biome returns to normal and a differnent region changed. Is that on purpose?

**Comment by DietmarKrause** [comment]
it seems that the region in the overworld that is tranfered to "the Hollow" is changing from one start of the world to the next start.

**Comment by furtabs** [comment]
Never seen this in my testing for the 1.4 update. Ill close this for now feel free to request to reopen
