### ISSUE TITLE
El Crash 1:

### ISSUE THREAD

**Issue by i509VCB** [AllTheMods/ATM-Fabric#2]
https://hastebin.com/ejeherefok.rb

**Comment by Martmists-GH** [comment]
This seems to happen on right-click (with any item or even air), though we have no clue what triggers it.

**Comment by MrGREGhimself** [comment]
Same issue here. I was trying to place the torch whilst being directly against the block.

In case it's needed:
https://hastebin.com/ecakozojav.rb

Edit:
Torches in off-hand. No item in "main" hand. No issue. 
But as soon as you place an item in your main hand and try to place the torch, crash.

**Comment by Martmists-GH** [comment]
I'm suspecting the offending mod to be BowInfinityFix, it'll be removed in the next update. If this stops happening by then, please close this issue.

**Comment by kjmaster1** [comment]
Removed BowInfinityFix like you suggested and still got the same crash after playing for a short time.

**Comment by theJERMwarfare** [comment]
I am getting the same crash many times when right clicking to try to place a torch or eat. I noticed that most of the times when I log back in my helmet is in my hot-bar and my sword is on my head.

Except for some cooked mutton I dropped all items including armor in a chest and could eat without crashing, at least for now. I am think that it may be the "Anything is a Hat" mod....maybe
