### ISSUE TITLE
Crafting recipe problems

### ISSUE THREAD

**Issue by Quu1337** [AllTheMods/ATM-Fabric#20]
Iron Barrel: Spruce barrel + 4 iron -> Iron barrel, doesnt work with any other wooden barrel.
Wood to iron barrel upgrade: cant be crafted, makes reinforced wood instead of the upgrade.
Beds are broke many ways, as reported already.

Will write more when i notice them

**Comment by furtabs** [comment]
Ill look tomorrow should be an easy fix

**Comment by furtabs** [comment]
couldnt find an easy fix seems an incompatibility in the mod
