### ISSUE TITLE
Nourish is not affected by foods that you eat

### ISSUE THREAD

**Issue by ExodiaJedi** [AllTheMods/ATM-Fabric#29]
No matter what food is eaten, nourish levels not raising.

Found in the Wiki for Nourish from the CurseForge page
https://github.com/emilyalexandra/nourish/wiki/Nourish-Tags

According to the documentation a json for each food type is needed in the config\nourish folder (of the ATF 3 root folder)

Examples of the files can be found here:
https://github.com/emilyalexandra/nourish/tree/master/src/main/resources/data/nourish/tags/items

I have attached them below as well. (appened .txt)

[carbohydrates.json.txt](https://github.com/AllTheMods/ATM-Fabric/files/5648241/carbohydrates.json.txt)
[fats.json.txt](https://github.com/AllTheMods/ATM-Fabric/files/5648242/fats.json.txt)
[fruit.json.txt](https://github.com/AllTheMods/ATM-Fabric/files/5648243/fruit.json.txt)
[protein.json.txt](https://github.com/AllTheMods/ATM-Fabric/files/5648244/protein.json.txt)
[sweets.json.txt](https://github.com/AllTheMods/ATM-Fabric/files/5648245/sweets.json.txt)
[vegetables.json.txt](https://github.com/AllTheMods/ATM-Fabric/files/5648246/vegetables.json.txt)

These files only include the default foods.

**Comment by furtabs** [comment]
Hrm. All the mods Fabric for 1.16 is being looked at. Tt that is strange

**Comment by furtabs** [comment]
Wait we don’t have nourish in our pack???

**Comment by ExodiaJedi** [comment]
found the files in:
\kubejs\data\nourish\tags\items

BUT they do not include vanilla minecraft foods (which is all i was eating)

The names for the default minecraft foods are in the files I attached

**Comment by furtabs** [comment]
Like I said we don’t use nurish

**Comment by ExodiaJedi** [comment]
so disable the mod?

**Comment by furtabs** [comment]
It shouldn’t even be installed  so yeah lul
