### ISSUE TITLE
[1.0] Crash when placing torches 

### ISSUE THREAD

**Issue by kjmaster1** [AllTheMods/ATM-Fabric#3]
I'm crashing when I place torches in a cave, could not be the torches but it happens when I'm placing torches so that's what I'm going with.
https://pastebin.com/vsNqf7JG

**Comment by i509VCB** [comment]
Exact same error here also. #2 (Once passively and another time trying to eat food)

**Comment by Martmists-GH** [comment]
Duplicate of #2
