### ISSUE TITLE
When an item is on head, right clicking anything crashes game (Server)

### ISSUE THREAD

**Issue by GrimmDZ** [AllTheMods/ATM-Fabric#6]
I have done this multiple times on accident haha, first with raw mutton, then iron nugget multiple times. Seems that whenever theres an item on my head when I shift right click anything from and to my inventory. Then I try to right click anything it crashes my game. 
Edit: I have armor on my head and it crashes my game. So it seems to be literally anything.

**Comment by Martmists-GH** [comment]
Removed the mod
