### ISSUE TITLE
Village underwater

### ISSUE THREAD

**Issue by GrimmDZ** [AllTheMods/ATM-Fabric#7]
![2019-12-21_17 55 21](https://user-images.githubusercontent.com/44906331/71315466-519a3900-241b-11ea-94a4-66b1d4e86df0.png)
![2019-12-21_17 54 18](https://user-images.githubusercontent.com/44906331/71315468-5363fc80-241b-11ea-9902-843839475f7d.png)
I came across a village that half of it is submersed underwater, usually the houses float but instead they are underwater at the floor. So is the farm and the market. The houses are all filled with water. And all the torches and plants aren't water logged.

**Comment by Martmists-GH** [comment]
Seems like an issue with Simplex Terrain, open an issue on their repo instead.

**Comment by GrimmDZ** [comment]
This is also on the server, forgot to say that if its important!

**Comment by Martmists-GH** [comment]
once it gets fixed in Simplex Terrain we'll merge the fix into our pack

**Comment by jaskarth** [comment]
Hi, developer of Simplex Terrain here. This is most likely a bug caused by vanilla code, but it's nothing that a good mixin or twenty can't solve.
