### ISSUE TITLE
Remove TBO

### ISSUE THREAD

**Issue by valoeghese** [AllTheMods/ATM-Fabric#8]
TheBiomeOverhaul is incompatible with other biome mods, and adding it to a mod pack is discouraged.

It was updated to 1.15 because of the small group of people who still use the mod in their worlds (especially a certain youtube channel with 1M subscribers).

**Comment by valoeghese** [comment]
_(Not to be confused with TBOClassic, which is fully compatible with other biome mods)_

**Comment by Martmists-GH** [comment]
Removed in 0.1.5
