### ISSUE TITLE
Vanilla blast furnace doesn't work for TR ores

### ISSUE THREAD

**Issue by Aplet123** [AllTheMods/ATM-Fabric#9]
The vanilla blast furnace can't smelt tech reborn ores like copper, lead, and silver, despite the vanilla furnace being able to smelt them.

**Comment by furtabs** [comment]
Hmm I’ll take a peak might need some data pack magic but it’s better to report this on Tech Reborn’s side

**Comment by furtabs** [comment]
https://github.com/TechReborn/TechReborn/issues/2037
